[package]
name = "spacedrive"
version = "0.1.0"
description = "The universal file manager."
authors = ["Spacedrive Technology Inc."]
default-run = "spacedrive"
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
tauri = { version = "1.3.0", features = ["api-all", "linux-protocol-headers", "macos-private-api"] }
rspc = { workspace = true, features = ["tauri"] }
httpz = { workspace = true, features = [
	"axum",
	"tauri",
] } # TODO: The `axum` feature should be only enabled on Linux but this currently can't be done: https://github.com/rust-lang/cargo/issues/1197
sd-core = { path = "../../../core", features = [
	"ffmpeg",
	"location-watcher",
	"heif",
] }
tokio = { workspace = true, features = ["sync"] }
window-shadows = "0.2.0"
tracing = "0.1.36"
serde = "1.0.145"
percent-encoding = "2.2.0"
http = "0.2.8"
opener = "0.6.1"
specta.workspace = true
tauri-specta = { workspace = true, features = ["typescript"] }
uuid = { version = "1.1.2", features = ["serde"] }

[target.'cfg(target_os = "linux")'.dependencies]
axum = { version = "0.6.4", features = ["headers", "query"] }
rand = "0.8.5"

[target.'cfg(target_os = "macos")'.dependencies]
sd-desktop-macos.path = "../crates/macos"

[build-dependencies]
tauri-build = { version = "1.3.0", features = [] }

[features]
default = ["custom-protocol"]
updater = ["tauri/updater"]
custom-protocol = ["tauri/custom-protocol"]
